### ISSUE TITLE
Generated URL for pulling an artifact is not correct

### ISSUE THREAD

**Issue by fellenberger** [rundeck-plugins/nexus-step-plugins#7]
Pulled code for the 1.0.1 release and built locally.  Deployed to a RHEL Rundeck 2.4.2 instance.  The generated URL for requesting the artifact no longer has “nexus” hard-coded (good), but it is also not taking into account that the server URL we have defined in framework.properties has a context name of “tis611” appended.  Therefore, the request for the artifact fails due to the constructed URL not being correct, as per the errors in the log below.

Job Log:
1: Workflow step executing: StepExecutionItem{type='nexus-deliver-artifact-step', keepgoingOnSuccess=false, hasFailureHandler=false}
**Requesting artifact from url:** http://servername/service/local/artifact/maven/redirect?g=org.talend.libraries&a=activation&v=6.0.0-SNAPSHOT&r=talend-custom-libs&p=jar
 
Failed executing step plugin [nexus-deliver-artifact-step]: java.lang.reflect.UndeclaredThrowableException at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1086) 
…
…
…
Caused by: com.dtolabs.rundeck.core.execution.workflow.steps.StepException: **Artifact not found in matching query:** [g:org.talend.libraries, a:activation, v:6.0.0-SNAPSHOT, r:talend-custom-libs, p:jar], server: **http://servername/tis611/**
 
 
This is what we have in framework.properties:
 
framework.plugin.WorkflowStep.nexus-deliver-artifact-step.nexus=http://servername/tis611/
framework.plugin.WorkflowStep.nexus-deliver-artifact-step.nexusUser=user
framework.plugin.WorkflowStep.nexus-deliver-artifact-step.nexusPassword=pass
framework.plugin.WorkflowStep.nexus-register-delivery-step.modelDirPath=/tmp

**Comment by grafjo** [comment]
hi @fellenberger 
this issue should be fixed by https://github.com/rundeck-plugins/nexus-step-plugins/pull/9

**Comment by fellenberger** [comment]
hi @grafjo 

Confirming that the commit for #9 fixed the issue!  I was able to successfully verify pulling of an artifact from our custom Nexus repository.  I built locally, so a release will need to be spun to pick up this fix as some point.  Thanks again.
